create extension if not exists pgcrypto;

create table if not exists public.words (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  word text not null,
  meaning text not null,
  part_of_speech text,
  phonetic text,
  example text,
  collocation text,
  memory_tip text,
  day integer,
  group_name text,
  created_at timestamptz not null default now(),
  unique (user_id, word)
);

create table if not exists public.study_records (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint not null references public.words(id) on delete cascade,
  answer text not null default '',
  is_correct boolean not null,
  created_at timestamptz not null default now()
);

create table if not exists public.mistakes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  word_id bigint not null references public.words(id) on delete cascade,
  wrong_answer text not null default '',
  error_count integer not null default 1 check (error_count > 0),
  status text not null default 'active' check (status in ('active', 'mastered')),
  last_wrong_at timestamptz not null default now(),
  unique (user_id, word_id)
);

create table if not exists public.notes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  content text not null default '',
  category text,
  tags text[] not null default '{}',
  source text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quizzes (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  quiz_type text not null default 'zh_to_en',
  total_questions integer not null default 0,
  correct_count integer not null default 0,
  wrong_count integer not null default 0,
  accuracy numeric(5,2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists study_records_user_created_idx on public.study_records(user_id, created_at desc);
create index if not exists mistakes_user_status_idx on public.mistakes(user_id, status);
create index if not exists notes_user_updated_idx on public.notes(user_id, updated_at desc);

alter table public.words enable row level security;
alter table public.study_records enable row level security;
alter table public.mistakes enable row level security;
alter table public.notes enable row level security;
alter table public.quizzes enable row level security;

create policy "Users manage own words" on public.words for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own study records" on public.study_records for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own mistakes" on public.mistakes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own notes" on public.notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage own quizzes" on public.quizzes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
